# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-10-04 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monta_user", "0008_alter_profile_address_alter_profile_bio_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("monta_fleet", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fleet",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Description of the fleet.",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="fleet",
            name="fleet_id",
            field=models.CharField(
                blank=True,
                help_text="Unique ID of the fleet.",
                max_length=15,
                null=True,
                unique=True,
                verbose_name="Fleet ID",
            ),
        ),
        migrations.AlterField(
            model_name="fleet",
            name="fleet_manager",
            field=models.ForeignKey(
                help_text="The user who manages this fleet",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fleets",
                related_query_name="fleet",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Fleet Manager",
            ),
        ),
        migrations.AlterField(
            model_name="fleet",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Is the fleet active?", verbose_name="Is Active"
            ),
        ),
        migrations.AlterField(
            model_name="fleet",
            name="name",
            field=models.CharField(
                help_text="Name of the fleet.",
                max_length=50,
                unique=True,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="fleet",
            name="organization",
            field=models.ForeignKey(
                help_text="Organization that the fleet belongs to.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fleets",
                related_query_name="fleet",
                to="monta_user.organization",
                verbose_name="Organization",
            ),
        ),
    ]
