# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-09-30 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monta_routes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="route",
            name="mileage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Mileage",
                max_digits=10,
                null=True,
                verbose_name="Mileage",
            ),
        ),
    ]
