# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-09-30 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monta_routes", "0002_alter_route_mileage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="route",
            old_name="mileage",
            new_name="distance",
        ),
    ]
