# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-09-30 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monta_routes", "0003_rename_mileage_route_distance"),
    ]
