# Generated by Django 4.1.2 on 2022-10-26 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monta_routes", "0005_alter_route_organization"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="route",
            name="duration",
        ),
    ]
