# Generated by Django 4.1.2 on 2022-10-26 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monta_routes", "0006_remove_route_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="duration",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Duration in seconds",
                null=True,
                verbose_name="Duration",
            ),
        ),
    ]
