# -*- coding: utf-8 -*-
# Generated by Django 4.1 on 2022-09-04 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monta", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="first_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="last_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
