# -*- coding: utf-8 -*-
# Generated by Django 4.1 on 2022-09-05 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("monta", "0002_profile_first_name_profile_last_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "driver_id",
                    models.SlugField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("first_name", models.CharField(blank=True, max_length=255, null=True)),
                ("last_name", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "Driver",
                "verbose_name_plural": "Drivers",
                "ordering": ["first_name", "last_name"],
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "location_id",
                    models.CharField(blank=True, max_length=10, null=True, unique=True),
                ),
                (
                    "location_slug",
                    models.SlugField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "address_line_1",
                    models.CharField(
                        blank=True, help_text="Address", max_length=100, null=True
                    ),
                ),
                (
                    "address_line_2",
                    models.CharField(
                        blank=True,
                        help_text="Address Line 2",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, help_text="City", max_length=100, null=True
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True, help_text="State", max_length=2, null=True
                    ),
                ),
                (
                    "zip_code",
                    models.PositiveIntegerField(blank=True, help_text="Zip", null=True),
                ),
            ],
            options={
                "verbose_name": "Location",
                "verbose_name_plural": "Locations",
                "ordering": ["organization", "description"],
            },
        ),
        migrations.AlterModelOptions(
            name="jobtitle",
            options={
                "ordering": ["name"],
                "verbose_name": "Job Title",
                "verbose_name_plural": "Job Titles",
            },
        ),
        migrations.AlterModelOptions(
            name="organization",
            options={
                "ordering": ["name"],
                "verbose_name": "Organization",
                "verbose_name_plural": "Organizations",
            },
        ),
        migrations.AlterModelOptions(
            name="profile",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Profile",
                "verbose_name_plural": "Profiles",
            },
        ),
        migrations.AlterField(
            model_name="montauser",
            name="username",
            field=models.CharField(db_index=True, max_length=30, unique=True),
        ),
        migrations.CreateModel(
            name="LocationContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contact_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "contact_email",
                    models.EmailField(blank=True, max_length=255, null=True),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, help_text="Phone", max_length=10, null=True
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="monta.location"
                    ),
                ),
            ],
            options={
                "verbose_name": "Location Contact",
                "verbose_name_plural": "Location Contacts",
                "ordering": ["location", "contact_name"],
            },
        ),
        migrations.AddField(
            model_name="location",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="monta.organization"
            ),
        ),
        migrations.CreateModel(
            name="DriverProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile_picture",
                    models.ImageField(blank=True, null=True, upload_to="drivers/"),
                ),
                ("bio", models.TextField(blank=True, null=True)),
                (
                    "address_line_1",
                    models.CharField(
                        blank=True, help_text="Address", max_length=255, null=True
                    ),
                ),
                (
                    "address_line_2",
                    models.CharField(
                        blank=True, help_text="Address", max_length=255, null=True
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, help_text="City", max_length=255, null=True
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True, help_text="State", max_length=2, null=True
                    ),
                ),
                (
                    "zip_code",
                    models.PositiveIntegerField(blank=True, help_text="Zip", null=True),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, help_text="Phone", max_length=10, null=True
                    ),
                ),
                (
                    "license_number",
                    models.CharField(
                        blank=True,
                        help_text="License Number",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "license_state",
                    models.CharField(
                        blank=True, help_text="License State", max_length=2, null=True
                    ),
                ),
                (
                    "license_expiration",
                    models.DateField(
                        blank=True, help_text="License Expiration", null=True
                    ),
                ),
                ("is_hazmat", models.BooleanField(default=False, help_text="Hazmat")),
                ("is_tanker", models.BooleanField(default=False, help_text="Tanker")),
                (
                    "is_double_triple",
                    models.BooleanField(default=False, help_text="Double/Triples"),
                ),
                (
                    "is_passenger",
                    models.BooleanField(default=False, help_text="Passenger"),
                ),
                (
                    "driver",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, to="monta.driver"
                    ),
                ),
            ],
            options={
                "verbose_name": "Driver Profile",
                "verbose_name_plural": "Driver Profiles",
                "ordering": ["driver"],
            },
        ),
        migrations.AddField(
            model_name="driver",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="monta.organization"
            ),
        ),
    ]
