# -*- coding: utf-8 -*-
# Generated by Django 4.1 on 2022-09-05 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("monta", "0003_driver_location_alter_jobtitle_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentClassification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="monta.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Classification",
                "verbose_name_plural": "Document Classifications",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DriverQualification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "dq_file",
                    models.FileField(
                        blank=True, null=True, upload_to="drivers/qualification"
                    ),
                ),
                ("dq_file_size", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "doc_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="monta.documentclassification",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="monta.driver"
                    ),
                ),
            ],
            options={
                "verbose_name": "Driver Qualification",
                "verbose_name_plural": "Driver Qualifications",
                "ordering": ["driver", "doc_class"],
            },
        ),
        migrations.CreateModel(
            name="DriverContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contact_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "contact_email",
                    models.EmailField(blank=True, max_length=255, null=True),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, help_text="Phone", max_length=10, null=True
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("is_emergency", models.BooleanField(default=False)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="monta.driver"
                    ),
                ),
            ],
            options={
                "verbose_name": "Driver Contact",
                "verbose_name_plural": "Driver Contacts",
                "ordering": ["driver", "contact_name"],
            },
        ),
    ]
