# -*- coding: utf-8 -*-
# Generated by Django 4.1 on 2022-09-05 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monta", "0004_documentclassification_driverqualification_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="middle_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="driver",
            name="first_name",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="driver",
            name="last_name",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
