# -*- coding: utf-8 -*-
# Generated by Django 4.1 on 2022-09-05 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monta", "0005_driver_middle_name_alter_driver_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="driver_id",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
