# -*- coding: utf-8 -*-
# Generated by Django 4.1 on 2022-09-05 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monta", "0006_alter_driver_driver_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Comment Type",
                "verbose_name_plural": "Comment Types",
                "ordering": ["name"],
            },
        ),
        migrations.RemoveField(
            model_name="driverprofile",
            name="bio",
        ),
        migrations.CreateModel(
            name="DriverComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "comment_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="monta.commenttype",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="monta.driver"
                    ),
                ),
            ],
            options={
                "verbose_name": "Driver Comment",
                "verbose_name_plural": "Driver Comments",
                "ordering": ["driver", "comment_type"],
            },
        ),
    ]
