# -*- coding: utf-8 -*-
# Generated by Django 4.1 on 2022-09-05 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monta", "0007_commenttype_remove_driverprofile_bio_drivercomment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drivercontact",
            name="is_emergency",
            field=models.BooleanField(default=False, help_text="Emergency Contact"),
        ),
        migrations.AlterField(
            model_name="drivercontact",
            name="is_primary",
            field=models.BooleanField(default=False, help_text="Primary Contact"),
        ),
    ]
