# -*- coding: utf-8 -*-
# Generated by Django 4.1 on 2022-09-06 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monta", "0008_alter_drivercontact_is_emergency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="org_timezone",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
