# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-09-06 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("monta", "0009_organization_org_timezone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="first_name",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="last_name",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="organization",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="monta.organization",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="title",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="monta.jobtitle",
            ),
            preserve_default=False,
        ),
    ]
