# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-09-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monta", "0010_alter_profile_first_name_alter_profile_last_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="driverprofile",
            name="email",
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="driverprofile",
            name="city",
            field=models.CharField(
                blank=True, help_text="City", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="driverprofile",
            name="license_number",
            field=models.CharField(
                default=1, help_text="License Number", max_length=100
            ),
            preserve_default=False,
        ),
    ]
