# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-09-08 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monta", "0011_driverprofile_email_alter_driverprofile_city_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
