# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-09-12 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monta", "0012_organizationsettings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="driver",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="drivercomment",
            name="comment_type",
        ),
        migrations.RemoveField(
            model_name="drivercomment",
            name="driver",
        ),
        migrations.RemoveField(
            model_name="drivercontact",
            name="driver",
        ),
        migrations.RemoveField(
            model_name="driverprofile",
            name="driver",
        ),
        migrations.RemoveField(
            model_name="driverqualification",
            name="doc_class",
        ),
        migrations.RemoveField(
            model_name="driverqualification",
            name="driver",
        ),
        migrations.DeleteModel(
            name="CommentType",
        ),
        migrations.DeleteModel(
            name="Driver",
        ),
        migrations.DeleteModel(
            name="DriverComment",
        ),
        migrations.DeleteModel(
            name="DriverContact",
        ),
        migrations.DeleteModel(
            name="DriverProfile",
        ),
        migrations.DeleteModel(
            name="DriverQualification",
        ),
    ]
