# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-09-12 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monta", "0013_remove_driver_organization_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="montauser",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="montauser",
            name="user_permissions",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="title",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="user",
        ),
    ]
