# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-09-12 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monta_user", "0001_initial"),
        ("monta", "0014_remove_montauser_groups_and_more"),
        ("monta_driver", "0002_alter_driver_organization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentclassification",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="monta_user.organization",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="monta_user.organization",
            ),
        ),
        migrations.DeleteModel(
            name="JobTitle",
        ),
        migrations.DeleteModel(
            name="MontaUser",
        ),
        migrations.DeleteModel(
            name="Organization",
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
