# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-09-26 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monta", "0016_alter_organizationsettings_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="locationcontact",
            name="location",
        ),
        migrations.DeleteModel(
            name="Location",
        ),
        migrations.DeleteModel(
            name="LocationContact",
        ),
    ]
