# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-09-27 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monta", "0017_remove_locationcontact_location_delete_location_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documentclassification",
            name="organization",
        ),
    ]
