# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-09-27 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monta_driver", "0026_alter_driverqualification_doc_class"),
        ("monta", "0018_remove_documentclassification_organization"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DocumentClassification",
        ),
    ]
