# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-09-19 00:02

import django.utils.timezone
import django_extensions.db.fields
import localflavor.us.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monta_user", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={
                "ordering": ["-created"],
                "verbose_name": "Profile",
                "verbose_name_plural": "Profiles",
            },
        ),
        migrations.RemoveField(
            model_name="jobtitle",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="jobtitle",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="jobtitle",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="jobtitle",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True, verbose_name="modified"
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="organization",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True, verbose_name="modified"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True, verbose_name="modified"
            ),
        ),
        migrations.AlterField(
            model_name="jobtitle",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="jobtitle",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="jobtitle",
            name="title_id",
            field=models.SlugField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Title ID",
            ),
        ),
        migrations.AlterField(
            model_name="montauser",
            name="date_joined",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Date Joined"
            ),
        ),
        migrations.AlterField(
            model_name="montauser",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="Email Address"
            ),
        ),
        migrations.AlterField(
            model_name="montauser",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is Active"),
        ),
        migrations.AlterField(
            model_name="montauser",
            name="is_staff",
            field=models.BooleanField(default=False, verbose_name="Is Staff"),
        ),
        migrations.AlterField(
            model_name="montauser",
            name="username",
            field=models.CharField(
                db_index=True, max_length=30, unique=True, verbose_name="Username"
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Organization Description"
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="name",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Organization Name"
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="org_id",
            field=models.SlugField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Organization ID",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="org_timezone",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                verbose_name="Organization Timezone",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="organizations/",
                verbose_name="Profile Picture",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="address",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Address"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True, null=True, verbose_name="Bio"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="city",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="City"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="email_verified",
            field=models.BooleanField(default=False, verbose_name="Email Verified"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="first_name",
            field=models.CharField(max_length=255, verbose_name="First Name"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="last_name",
            field=models.CharField(max_length=255, verbose_name="Last Name"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Phone Number"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profiles/",
                verbose_name="Profile Picture",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="state",
            field=localflavor.us.models.USStateField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="zip_code",
            field=localflavor.us.models.USZipCodeField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="jobtitle",
            index=models.Index(fields=["name"], name="monta_user__name_86ed09_idx"),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(fields=["name"], name="monta_user__name_a98456_idx"),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["-created"], name="monta_user__created_9a7f59_idx"
            ),
        ),
    ]
