# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-10-04 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monta_user", "0005_alter_profile_state_alter_profile_zip_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="address",
            field=models.CharField(default=1, max_length=100, verbose_name="Address"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="city",
            field=models.CharField(default=1, max_length=100, verbose_name="City"),
            preserve_default=False,
        ),
    ]
