# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-10-04 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monta_user", "0006_alter_profile_address_alter_profile_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Phone Number"
            ),
        ),
    ]
