# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-10-04 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monta_user", "0007_alter_profile_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="address",
            field=models.CharField(
                help_text="The address of the user",
                max_length=100,
                verbose_name="Address",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(
                blank=True,
                help_text="The bio of the user",
                null=True,
                verbose_name="Bio",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="city",
            field=models.CharField(
                help_text="The city of the user", max_length=100, verbose_name="City"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="email_verified",
            field=models.BooleanField(
                default=False,
                help_text="If the user has verified their email",
                verbose_name="Email Verified",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="first_name",
            field=models.CharField(
                help_text="The first name of the user",
                max_length=255,
                verbose_name="First Name",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="last_name",
            field=models.CharField(
                help_text="The last name of the user",
                max_length=255,
                verbose_name="Last Name",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="profiles",
                related_query_name="profile",
                to="monta_user.organization",
                verbose_name="Organization",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="The phone number of the user",
                max_length=50,
                null=True,
                verbose_name="Phone Number",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                help_text="The profile picture of the user",
                null=True,
                upload_to="profiles/",
                verbose_name="Profile Picture",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="title",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="profiles",
                related_query_name="profile",
                to="monta_user.jobtitle",
                verbose_name="Title",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="profile",
                related_query_name="profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
