# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-10-12 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monta_user", "0008_alter_profile_address_alter_profile_bio_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="address",
            new_name="address_line_1",
        ),
        migrations.AddField(
            model_name="profile",
            name="address_line_2",
            field=models.CharField(
                blank=True,
                help_text="The address of the user",
                max_length=100,
                null=True,
                verbose_name="Address Line 2",
            ),
        ),
    ]
