# Generated by Django 4.1.1 on 2022-10-14 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monta_user', '0009_rename_address_profile_address_line_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='montauser',
            name='email',
            field=models.EmailField(help_text='Required. A valid email address.', max_length=254, unique=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='montauser',
            name='username',
            field=models.CharField(db_index=True, help_text='Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=30, unique=True, verbose_name='Username'),
        ),
    ]
