# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-10-19 13:45

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monta_user", "0010_alter_montauser_email_alter_montauser_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="org_id",
            field=models.UUIDField(
                blank=True,
                default=uuid.uuid4,
                editable=False,
                null=True,
                unique=True,
                verbose_name="Organization ID",
            ),
        ),
    ]
