# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-10-19 16:16

from django.db import migrations
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monta_user", "0013_alter_montauser_username"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="montauser",
            name="stops_protect_redundant_updates",
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="montauser",
            trigger=pgtrigger.compiler.Trigger(
                name="stops_protect_redundant_updates",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.username = NEW.username AND OLD.email = NEW.email AND OLD.is_staff = NEW.is_staff)",
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="239cdf2278cff97fab3238ef2d00b02a35df7a9a",
                    operation="UPDATE",
                    pgid="pgtrigger_stops_protect_redundant_updates_ea400",
                    table="monta_user_montauser",
                    when="BEFORE",
                ),
            ),
        ),
    ]
