# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-09-12 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monta_user", "0001_initial"),
        ("monta_driver", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="monta_user.organization",
            ),
        ),
    ]
