# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-09-12 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("monta_user", "0001_initial"),
        ("monta_driver", "0002_alter_driver_organization"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fleet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50, unique=True)),
                ("fleet_id", models.CharField(max_length=10, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "fleet_manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="monta_user.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fleet",
                "verbose_name_plural": "Fleets",
                "ordering": ["name"],
            },
        ),
        migrations.AddIndex(
            model_name="fleet",
            index=models.Index(
                fields=["name", "fleet_id"], name="monta_drive_name_f9f353_idx"
            ),
        ),
    ]
