# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-09-12 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monta_driver", "0005_alter_fleet_fleet_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fleet",
            name="fleet_id",
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
