# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-09-13 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monta_driver", "0006_alter_fleet_fleet_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="driverprofile",
            name="email",
        ),
        migrations.RemoveField(
            model_name="driverprofile",
            name="phone",
        ),
        migrations.AlterField(
            model_name="drivercomment",
            name="driver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="monta_driver.driver"
            ),
        ),
        migrations.AlterField(
            model_name="drivercontact",
            name="driver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="monta_driver.driver"
            ),
        ),
        migrations.AlterField(
            model_name="driverprofile",
            name="driver",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="monta_driver.driver"
            ),
        ),
        migrations.AlterField(
            model_name="driverqualification",
            name="driver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="monta_driver.driver"
            ),
        ),
    ]
