# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-09-17 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("monta_user", "0001_initial"),
        ("monta_driver", "0008_alter_drivercontact_contact_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="driver",
            options={
                "ordering": ["-first_name"],
                "verbose_name": "Driver",
                "verbose_name_plural": "Drivers",
            },
        ),
        migrations.AlterModelOptions(
            name="driverprofile",
            options={
                "verbose_name": "Driver Profile",
                "verbose_name_plural": "Driver Profiles",
            },
        ),
        migrations.AlterField(
            model_name="driver",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="driver_organization",
                to="monta_user.organization",
            ),
        ),
        migrations.AlterField(
            model_name="drivercomment",
            name="driver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="monta_driver.driver",
            ),
        ),
        migrations.AlterField(
            model_name="drivercontact",
            name="driver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contacts",
                to="monta_driver.driver",
            ),
        ),
        migrations.AlterField(
            model_name="driverfleet",
            name="driver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="driver_fleets",
                to="monta_driver.driver",
            ),
        ),
        migrations.AlterField(
            model_name="driverprofile",
            name="driver",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to="monta_driver.driver",
            ),
        ),
        migrations.AlterField(
            model_name="driverqualification",
            name="driver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="driver_qualifications",
                to="monta_driver.driver",
            ),
        ),
        migrations.AddIndex(
            model_name="driver",
            index=models.Index(
                fields=["-first_name"], name="monta_drive_first_n_643302_idx"
            ),
        ),
    ]
