# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-09-17 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monta_driver", "0010_alter_driverfleet_driver"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="driverfleet",
            options={
                "ordering": ["-driver"],
                "verbose_name": "Driver Fleet",
                "verbose_name_plural": "Driver Fleets",
            },
        ),
        migrations.AddIndex(
            model_name="driverfleet",
            index=models.Index(
                fields=["-driver"], name="monta_drive_driver__2c1506_idx"
            ),
        ),
    ]
