# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-09-17 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monta_driver", "0012_alter_driver_fleet"),
    ]
