# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-09-17 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monta_driver", "0015_alter_driver_fleet_alter_driverfleet_driver_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="driver",
            name="fleet",
        ),
        migrations.AddField(
            model_name="fleet",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name="DriverFleet",
        ),
    ]
