# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-09-17 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monta_driver", "0016_remove_driver_fleet_fleet_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fleet",
            name="driver",
            field=models.ManyToManyField(
                related_name="fleet_driver", to="monta_driver.driver"
            ),
        ),
    ]
