# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-09-17 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monta_driver", "0017_fleet_driver"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fleet",
            name="driver",
        ),
    ]
