# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-09-17 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monta_driver", "0018_remove_fleet_driver"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="fleet",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="driver_fleet",
                to="monta_driver.fleet",
            ),
        ),
    ]
