# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-09-19 00:02

import datetime
from django.db import migrations, models
import django.utils.timezone
import django_extensions.db.fields
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ("monta_driver", "0020_alter_driver_fleet"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commenttype",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="commenttype",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="driver",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="driver",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="drivercomment",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="drivercomment",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="drivercontact",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="drivercontact",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="driverprofile",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="driverprofile",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="driverqualification",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="driverqualification",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="fleet",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="fleet",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="commenttype",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="commenttype",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True, verbose_name="modified"
            ),
        ),
        migrations.AddField(
            model_name="driver",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="driver",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True, verbose_name="modified"
            ),
        ),
        migrations.AddField(
            model_name="drivercomment",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="drivercomment",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True, verbose_name="modified"
            ),
        ),
        migrations.AddField(
            model_name="drivercontact",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="drivercontact",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True, verbose_name="modified"
            ),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True, verbose_name="modified"
            ),
        ),
        migrations.AddField(
            model_name="driverqualification",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2022, 9, 19, 0, 2, 2, 575659, tzinfo=datetime.timezone.utc
                ),
                verbose_name="created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="driverqualification",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True, verbose_name="modified"
            ),
        ),
        migrations.AddField(
            model_name="fleet",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fleet",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True, verbose_name="modified"
            ),
        ),
        migrations.AlterField(
            model_name="commenttype",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="commenttype",
            name="name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="driver",
            name="driver_id",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                unique=True,
                verbose_name="Driver ID",
            ),
        ),
        migrations.AlterField(
            model_name="driver",
            name="first_name",
            field=models.CharField(max_length=255, verbose_name="First Name"),
        ),
        migrations.AlterField(
            model_name="driver",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is Active"),
        ),
        migrations.AlterField(
            model_name="driver",
            name="last_name",
            field=models.CharField(max_length=255, verbose_name="Last Name"),
        ),
        migrations.AlterField(
            model_name="driver",
            name="middle_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Middle Name"
            ),
        ),
        migrations.AlterField(
            model_name="drivercomment",
            name="comment",
            field=models.TextField(blank=True, null=True, verbose_name="Comment"),
        ),
        migrations.AlterField(
            model_name="drivercontact",
            name="contact_email",
            field=models.EmailField(
                blank=True, max_length=255, null=True, verbose_name="Contact Email"
            ),
        ),
        migrations.AlterField(
            model_name="drivercontact",
            name="contact_name",
            field=models.CharField(max_length=255, verbose_name="Contact Name"),
        ),
        migrations.AlterField(
            model_name="drivercontact",
            name="contact_phone",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Contact Phone"
            ),
        ),
        migrations.AlterField(
            model_name="drivercontact",
            name="is_emergency",
            field=models.BooleanField(default=False, verbose_name="Is Emergency"),
        ),
        migrations.AlterField(
            model_name="drivercontact",
            name="is_primary",
            field=models.BooleanField(default=False, verbose_name="Is Primary"),
        ),
        migrations.AlterField(
            model_name="driverprofile",
            name="address_line_1",
            field=models.CharField(max_length=255, verbose_name="Address Line 1"),
        ),
        migrations.AlterField(
            model_name="driverprofile",
            name="address_line_2",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Address Line 2"
            ),
        ),
        migrations.AlterField(
            model_name="driverprofile",
            name="city",
            field=models.CharField(max_length=100, verbose_name="City"),
        ),
        migrations.AlterField(
            model_name="driverprofile",
            name="is_double_triple",
            field=models.BooleanField(
                default=False, verbose_name="Is Doubles / Triples"
            ),
        ),
        migrations.AlterField(
            model_name="driverprofile",
            name="is_hazmat",
            field=models.BooleanField(default=False, verbose_name="Is Hazmat"),
        ),
        migrations.AlterField(
            model_name="driverprofile",
            name="is_passenger",
            field=models.BooleanField(default=False, verbose_name="Is Passenger"),
        ),
        migrations.AlterField(
            model_name="driverprofile",
            name="is_tanker",
            field=models.BooleanField(default=False, verbose_name="Is Tanker"),
        ),
        migrations.AlterField(
            model_name="driverprofile",
            name="license_expiration",
            field=models.DateField(verbose_name="License Expiration"),
        ),
        migrations.AlterField(
            model_name="driverprofile",
            name="license_number",
            field=models.CharField(max_length=100, verbose_name="License Number"),
        ),
        migrations.AlterField(
            model_name="driverprofile",
            name="license_state",
            field=localflavor.us.models.USStateField(max_length=2),
        ),
        migrations.AlterField(
            model_name="driverprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="drivers/",
                verbose_name="Profile Picture",
            ),
        ),
        migrations.AlterField(
            model_name="driverprofile",
            name="state",
            field=localflavor.us.models.USStateField(max_length=2),
        ),
        migrations.AlterField(
            model_name="driverprofile",
            name="zip_code",
            field=localflavor.us.models.USZipCodeField(max_length=10),
        ),
        migrations.AlterField(
            model_name="driverqualification",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="driverqualification",
            name="dq_file",
            field=models.FileField(
                upload_to="drivers/qualification",
                verbose_name="Driver Qualification File",
            ),
        ),
        migrations.AlterField(
            model_name="driverqualification",
            name="dq_file_size",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Driver Qualification File Size"
            ),
        ),
        migrations.AlterField(
            model_name="driverqualification",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="fleet",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="fleet",
            name="fleet_id",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                unique=True,
                verbose_name="Fleet ID",
            ),
        ),
        migrations.AlterField(
            model_name="fleet",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is Active"),
        ),
        migrations.AlterField(
            model_name="fleet",
            name="name",
            field=models.CharField(max_length=50, unique=True, verbose_name="Name"),
        ),
        migrations.AddIndex(
            model_name="commenttype",
            index=models.Index(fields=["name"], name="monta_drive_name_99cda6_idx"),
        ),
        migrations.AddIndex(
            model_name="drivercomment",
            index=models.Index(
                fields=["driver", "comment_type"], name="monta_drive_driver__c90c0c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="drivercontact",
            index=models.Index(
                fields=["driver", "contact_name"], name="monta_drive_driver__0e14c6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="driverqualification",
            index=models.Index(
                fields=["driver", "doc_class"], name="monta_drive_driver__5d9dc6_idx"
            ),
        ),
    ]
