# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-09-19 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monta_driver", "0022_remove_fleet_fleet_manager_remove_fleet_organization"),
        ("monta_fleet", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="fleet",
            field=models.ManyToManyField(
                blank=True, related_name="driver_fleet", to="monta_fleet.fleet"
            ),
        ),
        migrations.DeleteModel(
            name="Fleet",
        ),
    ]
