# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-09-20 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monta_user", "0003_remove_organization_org_timezone"),
        ("monta_driver", "0023_alter_driver_fleet_delete_fleet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="drivers",
                to="monta_user.organization",
            ),
        ),
    ]
