# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-09-25 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monta_driver", "0024_alter_driver_organization"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="driver",
            options={
                "ordering": ["-first_name"],
                "permissions": [
                    ("view_all_drivers", "Can All Drivers"),
                    ("search_drivers", "Can search drivers"),
                ],
                "verbose_name": "Driver",
                "verbose_name_plural": "Drivers",
            },
        ),
    ]
