# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-09-29 15:56

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("monta_user", "0005_alter_profile_state_alter_profile_zip_code"),
        ("monta_driver", "0026_alter_driverqualification_doc_class"),
    ]

    operations = [
        migrations.CreateModel(
            name="DriverHour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "eight_hour_clock",
                    models.IntegerField(
                        blank=True,
                        help_text="The eight hour clock for the driver",
                        null=True,
                        verbose_name="Eight Hour Clock",
                    ),
                ),
                (
                    "eleven_hour_clock",
                    models.IntegerField(
                        blank=True,
                        help_text="The number of hours the driver has worked in the last 11 hours",
                        null=True,
                        verbose_name="Eleven Hour Clock",
                    ),
                ),
                (
                    "fourteen_hour_clock",
                    models.IntegerField(
                        blank=True,
                        help_text="The number of hours the driver has worked in the last 14 hours",
                        null=True,
                        verbose_name="14 Hour Clock",
                    ),
                ),
                (
                    "seventy_hour_clock",
                    models.IntegerField(
                        blank=True,
                        help_text="The number of hours the driver has worked in the last 70 hours",
                        null=True,
                        verbose_name="70 Hour Clock",
                    ),
                ),
                (
                    "violation_time",
                    models.IntegerField(
                        blank=True,
                        help_text="The number of hours the driver has worked in violation of the hours of service",
                        null=True,
                        verbose_name="Violation Time",
                    ),
                ),
                (
                    "consecutive_time_off",
                    models.IntegerField(
                        blank=True,
                        help_text="The number of hours the driver has been off duty or the sleeper berth",
                        null=True,
                        verbose_name="Consecutive Time Off",
                    ),
                ),
                (
                    "last_known_duty_status",
                    models.CharField(
                        blank=True,
                        help_text="The last known duty status of the driver",
                        max_length=255,
                        null=True,
                        verbose_name="Last Known Duty Status",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="driver_hours",
                        to="monta_driver.driver",
                        verbose_name="Driver",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="driver_hours",
                        to="monta_user.organization",
                        verbose_name="Organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Driver Hour",
                "verbose_name_plural": "Driver Hours",
                "ordering": ["driver"],
            },
        ),
        migrations.AddIndex(
            model_name="driverhour",
            index=models.Index(
                fields=["driver"], name="monta_drive_driver__6188c9_idx"
            ),
        ),
    ]
