# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-09-29 16:05

import django.db.models.deletion
import localflavor.us.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monta_customer", "0012_rename_is_primary_customercontact_primary_contact"),
        ("monta_driver", "0028_drivercomment_organization_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drivercontact",
            name="driver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contacts",
                related_query_name="contact",
                to="monta_driver.driver",
                verbose_name="Driver",
            ),
        ),
        migrations.AlterField(
            model_name="driverprofile",
            name="driver",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                related_query_name="profile",
                to="monta_driver.driver",
                verbose_name="Driver",
            ),
        ),
        migrations.AlterField(
            model_name="driverprofile",
            name="state",
            field=localflavor.us.models.USStateField(
                help_text="The state the driver lives in",
                max_length=2,
                verbose_name="State",
            ),
        ),
        migrations.AlterField(
            model_name="driverprofile",
            name="zip_code",
            field=localflavor.us.models.USZipCodeField(
                help_text="The zip code the driver lives in",
                max_length=10,
                verbose_name="Zip Code",
            ),
        ),
        migrations.AlterField(
            model_name="driverqualification",
            name="doc_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="driver_qualifications",
                related_query_name="driver_qualification",
                to="monta_customer.documentclassification",
                verbose_name="Document Classification",
            ),
        ),
        migrations.AlterField(
            model_name="driverqualification",
            name="driver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="driver_qualifications",
                related_query_name="driver_qualification",
                to="monta_driver.driver",
                verbose_name="Driver",
            ),
        ),
    ]
