# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-10-02 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("monta_user", "0005_alter_profile_state_alter_profile_zip_code"),
        ("monta_driver", "0029_alter_drivercontact_driver_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drivercomment",
            name="comment_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="comments",
                related_query_name="comment",
                to="monta_driver.commenttype",
                verbose_name="Comment Type",
            ),
        ),
        migrations.AlterField(
            model_name="drivercomment",
            name="driver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="driver_comments",
                related_query_name="driver_comment",
                to="monta_driver.driver",
                verbose_name="Driver",
            ),
        ),
        migrations.AlterField(
            model_name="drivercomment",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="driver_comments",
                related_query_name="driver_comment",
                to="monta_user.organization",
                verbose_name="Organization",
            ),
        ),
        migrations.AlterField(
            model_name="driverhour",
            name="driver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="driver_hours",
                related_query_name="driver_hour",
                to="monta_driver.driver",
                verbose_name="Driver",
            ),
        ),
        migrations.AlterField(
            model_name="driverhour",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="driver_hours",
                related_query_name="driver_hour",
                to="monta_user.organization",
                verbose_name="Organization",
            ),
        ),
    ]
