# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-10-07 15:48

from django.db import migrations
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ("monta_driver", "0031_alter_driver_fleet_alter_driver_organization"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="driver",
            options={
                "ordering": [django.db.models.functions.text.Lower("-first_name")],
                "permissions": [
                    ("view_all_drivers", "Can All Drivers"),
                    ("search_drivers", "Can search drivers"),
                ],
                "verbose_name": "Driver",
                "verbose_name_plural": "Drivers",
            },
        ),
    ]
