# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-10-09 17:46

import django.db.models.functions.text
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monta_driver", "0032_alter_driver_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="driver",
            options={
                "ordering": (django.db.models.functions.text.Lower("last_name"),),
                "permissions": [
                    ("view_all_drivers", "Can All Drivers"),
                    ("search_drivers", "Can search drivers"),
                ],
                "verbose_name": "Driver",
                "verbose_name_plural": "Drivers",
            },
        ),
    ]
