# -*- coding: utf-8 -*-
# Generated by Django 4.1.2 on 2022-10-20 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monta_user", "0017_jobtitle_organization"),
        ("monta_driver", "0033_alter_driver_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="commenttype",
            name="organization",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment_types",
                related_query_name="comment_type",
                to="monta_user.organization",
                verbose_name="Organization",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="organization",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="driver_profiles",
                related_query_name="driver_profile",
                to="monta_user.organization",
                verbose_name="Organization",
            ),
            preserve_default=False,
        ),
    ]
