# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-09-26 01:02

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import localflavor.us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("monta_user", "0004_remove_montauser_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "location_id",
                    models.SlugField(
                        help_text="Unique ID for this location.",
                        max_length=255,
                        unique=True,
                        verbose_name="Location ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the location.",
                        max_length=255,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the location.",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "address_line_1",
                    models.CharField(
                        blank=True,
                        help_text="Address Line 1",
                        max_length=255,
                        null=True,
                        verbose_name="Address Line 1",
                    ),
                ),
                (
                    "address_line_2",
                    models.CharField(
                        blank=True,
                        help_text="Address Line 2",
                        max_length=255,
                        null=True,
                        verbose_name="Address Line 2",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        help_text="City",
                        max_length=255,
                        null=True,
                        verbose_name="City",
                    ),
                ),
                ("state", localflavor.us.models.USStateField(max_length=2)),
                ("zip_code", localflavor.us.models.USZipCodeField(max_length=10)),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Longitude",
                        max_digits=9,
                        null=True,
                        verbose_name="Longitude",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Latitude",
                        max_digits=9,
                        null=True,
                        verbose_name="Latitude",
                    ),
                ),
                (
                    "place_id",
                    models.CharField(
                        blank=True,
                        help_text="Place ID",
                        max_length=255,
                        null=True,
                        verbose_name="Place ID",
                    ),
                ),
                (
                    "is_geocoded",
                    models.BooleanField(
                        default=False,
                        help_text="Is the location geocoded?",
                        verbose_name="Is Geocoded",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="monta_user.organization",
                        verbose_name="Organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Location",
                "verbose_name_plural": "Locations",
                "ordering": ("location_id", "name"),
            },
        ),
        migrations.CreateModel(
            name="LocationContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the contact.",
                        max_length=255,
                        verbose_name="Name",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Email of the contact.",
                        max_length=255,
                        null=True,
                        verbose_name="Email",
                    ),
                ),
                (
                    "phone",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Phone of the contact.",
                        null=True,
                        verbose_name="Phone",
                    ),
                ),
                (
                    "fax",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Fax of the contact.",
                        null=True,
                        verbose_name="Fax",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="monta_locations.location",
                        verbose_name="Location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Location Contact",
                "verbose_name_plural": "Location Contacts",
                "ordering": ("name",),
            },
        ),
        migrations.AddIndex(
            model_name="locationcontact",
            index=models.Index(fields=["name"], name="monta_locat_name_f5576d_idx"),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(
                fields=["location_id", "name"], name="monta_locat_locatio_a5621f_idx"
            ),
        ),
    ]
