# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-09-26 01:36

from django.db import migrations
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ("monta_locations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="state",
            field=localflavor.us.models.USStateField(
                help_text="State", max_length=2, verbose_name="State"
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="zip_code",
            field=localflavor.us.models.USZipCodeField(
                help_text="Zip Code", max_length=10, verbose_name="Zip Code"
            ),
        ),
    ]
