# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-09-30 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monta_locations", "0004_alter_location_location_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="latitude",
            field=models.FloatField(
                blank=True, help_text="Latitude", null=True, verbose_name="Latitude"
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="longitude",
            field=models.FloatField(
                blank=True, help_text="Longitude", null=True, verbose_name="Longitude"
            ),
        ),
    ]
