# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-10-07 15:48

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monta_driver", "0032_alter_driver_options"),
        ("monta_user", "0008_alter_profile_address_alter_profile_bio_and_more"),
        ("monta_locations", "0006_alter_location_organization"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocationComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "comment",
                    models.TextField(help_text="Comment", verbose_name="Comment"),
                ),
                (
                    "comment_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_comments",
                        related_query_name="location_comment",
                        to="monta_driver.commenttype",
                        verbose_name="Comment Type",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_comments",
                        related_query_name="location_comment",
                        to="monta_locations.location",
                        verbose_name="Location",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_comments",
                        related_query_name="location_comment",
                        to="monta_user.organization",
                        verbose_name="Organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Location Comment",
                "verbose_name_plural": "Location Comments",
                "ordering": ("comment_type",),
            },
        ),
        migrations.AddIndex(
            model_name="locationcomment",
            index=models.Index(
                fields=["comment_type"], name="monta_locat_comment_5382f7_idx"
            ),
        ),
    ]
