# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-10-10 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("monta_user", "0008_alter_profile_address_alter_profile_bio_and_more"),
        ("monta_locations", "0007_locationcomment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="locationcontact",
            name="organization",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="location_contacts",
                related_query_name="location_contact",
                to="monta_user.organization",
                verbose_name="Organization",
            ),
            preserve_default=False,
        ),
    ]
