# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-09-26 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monta_customer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="name",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
