# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-09-26 02:53

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ("monta_customer", "0002_customer_description_customer_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={
                "ordering": ["customer_id"],
                "verbose_name": "Customer",
                "verbose_name_plural": "Customers",
            },
        ),
        migrations.RemoveField(
            model_name="customer",
            name="description",
        ),
        migrations.AddField(
            model_name="customer",
            name="address_line_1",
            field=models.CharField(
                default=1, max_length=255, verbose_name="Address Line 1"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customer",
            name="address_line_2",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Address Line 2"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="city",
            field=models.CharField(default=1, max_length=255, verbose_name="City"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customer",
            name="customer_id",
            field=models.SlugField(
                default=1,
                help_text="Customer ID",
                max_length=255,
                unique=True,
                verbose_name="Customer ID",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customer",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Is this customer active?"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="state",
            field=localflavor.us.models.USStateField(
                default=1, max_length=2, verbose_name="State"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customer",
            name="zip_code",
            field=localflavor.us.models.USZipCodeField(
                default=1, max_length=10, verbose_name="Zip Code"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customer",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["customer_id"], name="monta_custo_custome_f3ae63_idx"
            ),
        ),
    ]
