# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-09-26 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "monta_customer",
            "0003_alter_customer_options_remove_customer_description_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="customer_id",
            field=models.SlugField(
                blank=True,
                help_text="Customer ID",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Customer ID",
            ),
        ),
    ]
