# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-09-27 04:42

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monta_user", "0004_remove_montauser_is_active"),
        ("monta_customer", "0005_customerbillingprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerbillingprofile",
            name="customer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="billing_profiles",
                related_query_name="billing_profile",
                to="monta_customer.customer",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="DocumentClassification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="Name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="monta_user.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Classification",
                "verbose_name_plural": "Document Classifications",
                "ordering": ["name"],
            },
        ),
    ]
