# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-09-27 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monta_customer", "0009_alter_customerbillingprofile_customer_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customerbillingprofile",
            options={
                "ordering": ["name"],
                "verbose_name": "Customer Billing Profile",
                "verbose_name_plural": "Customer Billing Profiles",
            },
        ),
        migrations.AlterField(
            model_name="customerbillingprofile",
            name="name",
            field=models.CharField(
                help_text="Name", max_length=100, unique=True, verbose_name="Name"
            ),
        ),
        migrations.AddIndex(
            model_name="customerbillingprofile",
            index=models.Index(fields=["name"], name="monta_custo_name_d6bbb5_idx"),
        ),
    ]
