# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-09-27 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monta_customer", "0011_customercontact_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customercontact",
            old_name="is_primary",
            new_name="primary_contact",
        ),
    ]
