# -*- coding: utf-8 -*-
# Generated by Django 4.1.2 on 2022-10-20 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monta_customer", "0013_alter_customerbillingprofile_organization_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerbillingprofile",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Is this billing profile active?"
            ),
        ),
    ]
