# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-09-26 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monta_user", "0004_remove_montauser_is_active"),
        ("monta_hazardous_material", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hazardousclass",
            options={
                "ordering": ["name"],
                "verbose_name": "Hazardous Class",
                "verbose_name_plural": "Hazardous Classes",
            },
        ),
        migrations.AddField(
            model_name="hazardousclass",
            name="organization",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hazardous_class",
                to="monta_user.organization",
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="hazardousclass",
            index=models.Index(fields=["name"], name="monta_hazar_name_1cdd40_idx"),
        ),
    ]
