# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-10-13 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "monta_hazardous_material",
            "0004_hazardousmaterial_remove_hazardousclass_organization",
        ),
        ("monta_user", "0009_rename_address_profile_address_line_1_and_more"),
        ("monta_order", "0042_order_bol_number_order_consignee_ref_num_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HazardousClass",
        ),
        migrations.AddField(
            model_name="hazardousmaterial",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hazardous_materials",
                related_query_name="hazardous_material",
                to="monta_user.organization",
                verbose_name="Organization",
            ),
        ),
    ]
