# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-09-19 19:11

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("monta_user", "0003_remove_organization_org_timezone"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "timezone",
                    models.CharField(default="America/New_York", max_length=255),
                ),
                ("language", models.CharField(default="en", max_length=255)),
                ("currency", models.CharField(default="USD", max_length=255)),
                ("date_format", models.CharField(default="MM/DD/YYYY", max_length=255)),
                ("time_format", models.CharField(default="HH:mm", max_length=255)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="monta_user.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization Settings",
                "verbose_name_plural": "Organization Settings",
            },
        ),
    ]
