# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-09-26 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monta_organization", "0002_googleapi_googleapi_monta_organ_name_1e86a8_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="googleapi",
            name="api_key",
            field=models.CharField(
                blank=True,
                help_text="Google Maps API Key",
                max_length=255,
                null=True,
                verbose_name="API Key",
            ),
        ),
        migrations.AlterField(
            model_name="googleapi",
            name="client_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Client ID"
            ),
        ),
        migrations.AlterField(
            model_name="googleapi",
            name="client_secret",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Client Secret"
            ),
        ),
        migrations.AlterField(
            model_name="googleapi",
            name="name",
            field=models.CharField(
                choices=[
                    ("google_maps", "Google Maps"),
                    ("google_places", "Google Places"),
                ],
                max_length=255,
                verbose_name="Name",
            ),
        ),
    ]
