# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-09-26 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monta_organization", "0004_integration_delete_googleapi_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="integration",
            options={
                "ordering": ["name"],
                "verbose_name": "Integration",
                "verbose_name_plural": "Integrations",
            },
        ),
        migrations.AlterField(
            model_name="integration",
            name="api_key",
            field=models.CharField(
                blank=True,
                help_text="API Key",
                max_length=255,
                null=True,
                verbose_name="API Key",
            ),
        ),
    ]
