# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-09-27 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monta_user", "0004_remove_montauser_is_active"),
        (
            "monta_organization",
            "0005_alter_integration_options_alter_integration_api_key",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="integration",
            name="is_active",
            field=models.BooleanField(
                default=False,
                help_text="Is the integration active?",
                verbose_name="Is Active",
            ),
        ),
        migrations.AlterField(
            model_name="integration",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="integrations",
                to="monta_user.organization",
            ),
        ),
        migrations.AlterField(
            model_name="organizationsettings",
            name="currency",
            field=models.CharField(
                default="USD",
                help_text="The currency that the organization uses",
                max_length=255,
                verbose_name="Currency",
            ),
        ),
        migrations.AlterField(
            model_name="organizationsettings",
            name="date_format",
            field=models.CharField(
                default="MM/DD/YYYY",
                help_text="Date Format",
                max_length=255,
                verbose_name="Date Format",
            ),
        ),
        migrations.AlterField(
            model_name="organizationsettings",
            name="language",
            field=models.CharField(
                default="en",
                help_text="The language of the organization",
                max_length=255,
                verbose_name="Language",
            ),
        ),
        migrations.AlterField(
            model_name="organizationsettings",
            name="organization",
            field=models.ForeignKey(
                help_text="The organization that the settings belong to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="settings",
                to="monta_user.organization",
                verbose_name="Organization",
            ),
        ),
        migrations.AlterField(
            model_name="organizationsettings",
            name="time_format",
            field=models.CharField(
                default="HH:mm",
                help_text="Time Format",
                max_length=255,
                verbose_name="Time Format",
            ),
        ),
        migrations.AlterField(
            model_name="organizationsettings",
            name="timezone",
            field=models.CharField(
                default="America/New_York",
                help_text="The timezone of the organization",
                max_length=255,
                verbose_name="Timezone",
            ),
        ),
    ]
