# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-09-30 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monta_organization", "0007_alter_organizationsettings_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationsettings",
            name="mileage_unit",
            field=models.CharField(
                choices=[("metric", "Metric"), ("imperial", "Imperial")],
                default="imperial",
                help_text="The mileage unit that the organization uses",
                max_length=255,
                verbose_name="Mileage Unit",
            ),
        ),
    ]
