# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-09-30 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monta_organization", "0008_organizationsettings_mileage_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationsettings",
            name="traffic_model",
            field=models.CharField(
                choices=[
                    ("best_guess", "Best Guess"),
                    ("optimistic", "Optimistic"),
                    ("pessimistic", "Pessimistic"),
                ],
                default="best_guess",
                help_text="The traffic model that the organization uses",
                max_length=255,
                verbose_name="Traffic Model",
            ),
        ),
    ]
