# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-09-20 11:25

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import localflavor.us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("monta_user", "0003_remove_organization_org_timezone"),
        ("monta_driver", "0024_alter_driver_organization"),
    ]

    operations = [
        migrations.CreateModel(
            name="EquipmentType",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "equip_type_id",
                    models.CharField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Equipment Type ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="Equipment Type Name"),
                ),
                (
                    "description",
                    models.CharField(
                        max_length=200, verbose_name="Equipment Type Description"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="monta_user.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Equipment Type",
                "verbose_name_plural": "Equipment Types",
                "ordering": ["equip_type_id"],
            },
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "equip_id",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Equipment ID"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "vin_number",
                    models.CharField(
                        blank=True,
                        max_length=17,
                        null=True,
                        verbose_name="Vehicle Identification Number",
                    ),
                ),
                (
                    "vehicle_model",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Vehicle Model",
                    ),
                ),
                (
                    "vehicle_make",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Vehicle Make",
                    ),
                ),
                (
                    "vehicle_year",
                    models.DateField(
                        blank=True, null=True, verbose_name="Vehicle Year"
                    ),
                ),
                ("state", localflavor.us.models.USStateField(max_length=2)),
                (
                    "equipment_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="equipment_type",
                        to="monta_equipment.equipmenttype",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="equipment",
                        to="monta_user.organization",
                    ),
                ),
                (
                    "primary_driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="primary_driver",
                        to="monta_driver.driver",
                    ),
                ),
                (
                    "secondary_driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secondary_driver",
                        to="monta_driver.driver",
                    ),
                ),
            ],
            options={
                "verbose_name": "Equipment",
                "verbose_name_plural": "Equipment",
                "ordering": ["equip_id"],
            },
        ),
        migrations.AddIndex(
            model_name="equipmenttype",
            index=models.Index(
                fields=["equip_type_id"], name="monta_equip_equip_t_7c885a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="equipment",
            index=models.Index(
                fields=["equip_id"], name="monta_equip_equip_i_9e02ed_idx"
            ),
        ),
    ]
