# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-09-22 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("monta_equipment", "0002_alter_equipmenttype_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="EquipmentPermit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Permit Name")),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Permit Description",
                    ),
                ),
                (
                    "permit_file",
                    models.FileField(upload_to="permits/", verbose_name="Permit File"),
                ),
                (
                    "permit_file_size",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Permit File Size"
                    ),
                ),
                (
                    "deletion_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deletion Date"
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment",
                        to="monta_equipment.equipment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Equipment Permit",
                "verbose_name_plural": "Equipment Permits",
                "ordering": ["name"],
            },
        ),
        migrations.AddIndex(
            model_name="equipmentpermit",
            index=models.Index(fields=["name"], name="monta_equip_name_65df22_idx"),
        ),
    ]
