# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-10-02 23:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("monta_driver", "0030_alter_drivercomment_comment_type_and_more"),
        ("monta_user", "0005_alter_profile_state_alter_profile_zip_code"),
        ("monta_equipment", "0005_alter_equipment_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="equipment_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="equipments",
                related_query_name="equipment",
                to="monta_equipment.equipmenttype",
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="equipments",
                related_query_name="equipment",
                to="monta_user.organization",
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="primary_driver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="equipment",
                related_query_name="equipment",
                to="monta_driver.driver",
            ),
        ),
        migrations.AlterField(
            model_name="equipmentpermit",
            name="equipment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="equipment_permits",
                related_query_name="equipment_permit",
                to="monta_equipment.equipment",
            ),
        ),
        migrations.AlterField(
            model_name="equipmentpermit",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="equipment_permits",
                related_query_name="equipment_permit",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="equipmenttype",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="equipment_types",
                related_query_name="equipment_type",
                to="monta_user.organization",
                verbose_name="Organization",
            ),
        ),
    ]
