# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-10-14 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("monta_user", "0010_alter_montauser_email_alter_montauser_username"),
        ("monta_driver", "0033_alter_driver_options"),
        ("monta_equipment", "0006_alter_equipment_equipment_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipmentpermit",
            name="organization",
            field=models.ForeignKey(
                default=1,
                help_text="The organization the equipment permit belongs to.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="equipment_permits",
                related_query_name="equipment_permit",
                to="monta_user.organization",
                verbose_name="Organization",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="equipment",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Description of the equipment.",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="equip_id",
            field=models.CharField(
                help_text="Unique identifier for the equipment.",
                max_length=50,
                unique=True,
                verbose_name="Equipment ID",
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="equipment_type",
            field=models.ForeignKey(
                help_text="The type of equipment.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="equipments",
                related_query_name="equipment",
                to="monta_equipment.equipmenttype",
                verbose_name="Equipment Type",
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Whether the equipment is active or not.",
                verbose_name="Is Active",
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="organization",
            field=models.ForeignKey(
                help_text="The organization the equipment belongs to.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="equipments",
                related_query_name="equipment",
                to="monta_user.organization",
                verbose_name="Organization",
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="primary_driver",
            field=models.ForeignKey(
                help_text="Primary driver of the equipment.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="equipments",
                related_query_name="equipment",
                to="monta_driver.driver",
                verbose_name="Primary Driver",
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="secondary_driver",
            field=models.ForeignKey(
                blank=True,
                help_text="Secondary driver of the equipment.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="equipments_secondary",
                related_query_name="equipment_secondary",
                to="monta_driver.driver",
                verbose_name="Secondary Driver",
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="vehicle_license_expiration",
            field=models.DateField(
                blank=True,
                help_text="Expiration date of the vehicle license plate.",
                null=True,
                verbose_name="Vehicle License Expiration",
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="vehicle_make",
            field=models.CharField(
                blank=True,
                help_text="Make of the vehicle.",
                max_length=255,
                null=True,
                verbose_name="Vehicle Make",
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="vehicle_model",
            field=models.CharField(
                blank=True,
                help_text="Model of the vehicle.",
                max_length=255,
                null=True,
                verbose_name="Vehicle Model",
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="vehicle_year",
            field=models.DateField(
                blank=True,
                help_text="Year of the vehicle.",
                null=True,
                verbose_name="Vehicle Year",
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="vin_number",
            field=models.CharField(
                blank=True,
                help_text="Vehicle Identification Number.",
                max_length=17,
                null=True,
                verbose_name="Vehicle Identification Number",
            ),
        ),
    ]
