# -*- coding: utf-8 -*-
# Generated by Django 4.1.2 on 2022-10-20 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monta_equipment", "0008_alter_equipment_secondary_driver"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="equipmentpermit",
            name="deletion_date",
        ),
    ]
