# Generated by Django 4.1.2 on 2022-10-26 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monta_equipment", "0009_remove_equipmentpermit_deletion_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipmenttype",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="Equipment Type Description",
                max_length=200,
                null=True,
                verbose_name="Equipment Type Description",
            ),
        ),
        migrations.AlterField(
            model_name="equipmenttype",
            name="equip_type_id",
            field=models.CharField(
                help_text="Equipment Type ID",
                max_length=50,
                primary_key=True,
                serialize=False,
                verbose_name="Equipment Type ID",
            ),
        ),
        migrations.AlterField(
            model_name="equipmenttype",
            name="name",
            field=models.CharField(
                help_text="Equipment Type Name",
                max_length=50,
                verbose_name="Equipment Type Name",
            ),
        ),
    ]
