#!/usr/bin/env bash
: '
COPYRIGHT 2022 MONTA

This file is part of Monta.

Monta is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Monta is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Monta.  If not, see <https://www.gnu.org/licenses/>.

-------------------------------------------------------------------------------

This is intended to create a view.py file for a Django app. It will create the
view.py file and add the necessary imports and code to it.
'

# Build the Test Boilerplate file
echo "Building Test Boilerplate file..."
# Remove all the text in the settings file
echo "" >generated-test.py

# get the current date
date=$(date)

echo "# -*- coding: utf-8 -*-" >generated-test.py
echo '"""
FILE GENERATED BY MONTA AUTO BUILDER ON '$date'

COPYRIGHT 2022 MONTA

This file is part of Monta.

Monta is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Monta is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Monta.  If not, see <https://www.gnu.org/licenses/>.

-------------------------------------------------------------------------------
"""

from django.test import TestCase


class NameTest(TestCase):
    def setUp(self) -> None:
        pass

    def test_create_name(self) -> None:
        pass

    def test_get_name(self) -> None:
        pass

    def test_update_name(self) -> None:
        pass

    def test_delete_name(self) -> None:
        pass
' >>generated-test.py
echo "Done!"