# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-09-26 03:02

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdditionalCharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "verbose_name": "Additional Charge",
                "verbose_name_plural": "Additional Charges",
                "ordering": ["name"],
            },
        ),
        migrations.AddIndex(
            model_name="additionalcharge",
            index=models.Index(fields=["name"], name="monta_billi_name_4872c7_idx"),
        ),
    ]
