# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-09-27 03:59

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        (
            "monta_order",
            "0021_rename_freight_charge_order_freight_charge_amount_and_more",
        ),
        ("monta_billing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChargeType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Name of Charge Type"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Description of Charge Type"
                    ),
                ),
            ],
            options={
                "verbose_name": "Charge Type",
                "verbose_name_plural": "Charge Types",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="additionalcharge",
            name="order",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="additional_charges",
                related_query_name="additional_charge",
                to="monta_order.order",
                verbose_name="Order",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="additionalcharge",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Amount"
            ),
        ),
        migrations.AlterField(
            model_name="additionalcharge",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="additionalcharge",
            name="name",
            field=models.CharField(
                max_length=255,
                unique=True,
                verbose_name="Name of the additional charge",
            ),
        ),
        migrations.AddIndex(
            model_name="chargetype",
            index=models.Index(fields=["name"], name="monta_billi_name_47781d_idx"),
        ),
        migrations.AddField(
            model_name="additionalcharge",
            name="charge_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="additional_charges",
                related_query_name="additional_charge",
                to="monta_billing.chargetype",
                verbose_name="Charge Type",
            ),
            preserve_default=False,
        ),
    ]
