# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-09-27 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monta_billing", "0002_chargetype_additionalcharge_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="additionalcharge",
            name="unit",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Number of units of the charge",
                verbose_name="Unit",
            ),
        ),
    ]
