# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-09-27 21:55

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("monta_user", "0004_remove_montauser_is_active"),
        ("monta_order", "0029_order_billed"),
        ("monta_billing", "0005_billingqueue"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="billingqueue",
            options={
                "verbose_name": "Billing Queue",
                "verbose_name_plural": "Billing Queues",
            },
        ),
        migrations.CreateModel(
            name="BillingException",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        verbose_name="Name of the billing exception",
                    ),
                ),
                (
                    "exception_type",
                    models.CharField(
                        choices=[
                            ("PAPERWORK", "Paperwork"),
                            ("CHARGE", "Charge"),
                            ("CREDIT", "Credit"),
                            ("OTHER", "Other"),
                        ],
                        max_length=10,
                        verbose_name="Exception Type",
                    ),
                ),
                (
                    "exception",
                    models.TextField(blank=True, null=True, verbose_name="Exception"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="billing_exceptions",
                        related_query_name="billing_exception",
                        to="monta_order.order",
                        verbose_name="Order",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="billing_exceptions",
                        related_query_name="billing_exception",
                        to="monta_user.organization",
                        verbose_name="Organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Billing Exception",
                "verbose_name_plural": "Billing Exceptions",
                "ordering": ["name"],
            },
        ),
        migrations.AddIndex(
            model_name="billingexception",
            index=models.Index(fields=["name"], name="monta_billi_name_f8373b_idx"),
        ),
    ]
