# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-09-27 22:10

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("monta_user", "0004_remove_montauser_is_active"),
        ("monta_order", "0029_order_billed"),
        ("monta_billing", "0006_alter_billingqueue_options_billingexception_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BillingHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "batch_name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Batch Name"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="billing_histories",
                        related_query_name="billing_history",
                        to="monta_order.order",
                        verbose_name="Order",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="billing_histories",
                        related_query_name="billing_history",
                        to="monta_user.organization",
                        verbose_name="Organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Billing History",
                "verbose_name_plural": "Billing Histories",
                "ordering": ["batch_name"],
            },
        ),
        migrations.AddIndex(
            model_name="billinghistory",
            index=models.Index(
                fields=["batch_name"], name="monta_billi_batch_n_2b3d3b_idx"
            ),
        ),
    ]
