# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-09-29 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monta_billing", "0007_billinghistory_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="billinghistory",
            name="bill_type",
            field=models.CharField(
                choices=[
                    ("INVOICE", "Invoice"),
                    ("CREDIT", "Credit"),
                    ("DEBIT", "Debit"),
                    ("OTHER", "Other"),
                ],
                default="INVOICE",
                max_length=10,
                verbose_name="Bill Type",
            ),
        ),
        migrations.AddField(
            model_name="billingqueue",
            name="bill_type",
            field=models.CharField(
                choices=[
                    ("INVOICE", "Invoice"),
                    ("CREDIT", "Credit"),
                    ("DEBIT", "Debit"),
                    ("OTHER", "Other"),
                ],
                default="INVOICE",
                max_length=10,
                verbose_name="Bill Type",
            ),
        ),
    ]
