# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-09-29 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monta_billing", "0010_billingqueue_sub_total"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingqueue",
            name="sub_total",
            field=models.DecimalField(
                decimal_places=2, max_digits=100, verbose_name="Sub Total"
            ),
        ),
    ]
