# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-09-29 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monta_billing", "0012_alter_billingqueue_sub_total"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="billingqueue",
            options={
                "ordering": ["order"],
                "verbose_name": "Billing Queue",
                "verbose_name_plural": "Billing Queues",
            },
        ),
        migrations.RemoveField(
            model_name="billingqueue",
            name="sub_total",
        ),
        migrations.AddField(
            model_name="billingqueue",
            name="other_charge_total",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total of all other charges on the order",
                max_digits=10,
                null=True,
                verbose_name="Other Charge Total",
            ),
        ),
        migrations.AddField(
            model_name="billingqueue",
            name="total_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total amount of the order",
                max_digits=10,
                null=True,
                verbose_name="Total Amount",
            ),
        ),
        migrations.AddIndex(
            model_name="billingqueue",
            index=models.Index(fields=["order"], name="monta_billi_order_i_d098ac_idx"),
        ),
    ]
