# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-10-03 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monta_billing", "0013_alter_billingqueue_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="billingexception",
            options={
                "verbose_name": "Billing Exception",
                "verbose_name_plural": "Billing Exceptions",
            },
        ),
        migrations.RemoveIndex(
            model_name="billingexception",
            name="monta_billi_name_f8373b_idx",
        ),
        migrations.RemoveField(
            model_name="billingexception",
            name="name",
        ),
    ]
