# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-10-03 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monta_billing", "0014_alter_billingexception_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="billingexception",
            old_name="exception",
            new_name="exception_message",
        ),
    ]
