# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-10-03 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monta_billing", "0016_alter_billinghistory_bill_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billinghistory",
            name="batch_name",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Batch Name",
            ),
        ),
        migrations.AlterField(
            model_name="billinghistory",
            name="bill_type",
            field=models.CharField(
                choices=[
                    ("INVOICE", "Invoice"),
                    ("CREDIT", "Credit"),
                    ("DEBIT", "Debit"),
                    ("OTHER", "Other"),
                ],
                default="INVOICE",
                max_length=10,
                verbose_name="Bill Type",
            ),
        ),
    ]
