# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-10-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monta_billing", "0017_alter_billinghistory_batch_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billinghistory",
            name="sub_total",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Sub Total",
            ),
        ),
    ]
