# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-10-03 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monta_billing", "0018_alter_billinghistory_sub_total"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="billingqueue",
            options={
                "ordering": ["order"],
                "permissions": [("transfer_to_billing", "Can Transfer to Billing")],
                "verbose_name": "Billing Queue",
                "verbose_name_plural": "Billing Queues",
            },
        ),
    ]
