# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-10-03 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monta_billing", "0019_alter_billingqueue_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="billingqueue",
            options={
                "ordering": ["order"],
                "permissions": [
                    ("transfer_to_billing", "Can Transfer to Billing"),
                    ("bill_orders", "Can Bill Orders"),
                    ("re_bill_orders", "Can Re Bill Orders"),
                ],
                "verbose_name": "Billing Queue",
                "verbose_name_plural": "Billing Queues",
            },
        ),
    ]
