# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-10-03 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("monta_user", "0005_alter_profile_state_alter_profile_zip_code"),
        ("monta_billing", "0020_alter_billingqueue_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="additionalcharge",
            name="organization",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="additional_charges",
                related_query_name="additional_charge",
                to="monta_user.organization",
                verbose_name="Organization",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="chargetype",
            name="organization",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="charge_types",
                related_query_name="charge_type",
                to="monta_user.organization",
                verbose_name="Organization",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="additionalcharge",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Amount of the charge",
                max_digits=10,
                verbose_name="Amount",
            ),
        ),
    ]
