# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-10-09 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monta_billing", "0021_additionalcharge_organization_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="chargetype",
            name="monta_billi_name_47781d_idx",
        ),
    ]
