# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-10-12 04:23

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("monta_billing", "0022_remove_chargetype_monta_billi_name_47781d_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="RevenueCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Code of the Revenue Code",
                        max_length=255,
                        unique=True,
                        verbose_name="Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the Revenue Code",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
            ],
            options={
                "verbose_name": "Revenue Code",
                "verbose_name_plural": "Revenue Codes",
                "ordering": ["code"],
            },
        ),
        migrations.AddIndex(
            model_name="revenuecode",
            index=models.Index(fields=["code"], name="monta_billi_code_4d5c73_idx"),
        ),
    ]
