# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-10-12 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monta_billing", "0023_revenuecode_revenuecode_monta_billi_code_4d5c73_idx"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="revenuecode",
            name="monta_billi_code_4d5c73_idx",
        ),
    ]
