# Generated by Django 4.1.1 on 2022-10-12 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monta_billing", "0024_remove_revenuecode_monta_billi_code_4d5c73_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="revenuecode",
            name="code",
            field=models.CharField(
                help_text="Code of the Revenue Code",
                max_length=5,
                unique=True,
                verbose_name="Code",
            ),
        ),
    ]
