# Generated by Django 4.1.1 on 2022-10-12 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("monta_user", "0008_alter_profile_address_alter_profile_bio_and_more"),
        ("monta_billing", "0025_alter_revenuecode_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="revenuecode",
            name="organization",
            field=models.ForeignKey(
                default=1,
                help_text="Organization that the revenue code belongs to.",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="revenue_codes",
                related_query_name="revenue_code",
                to="monta_user.organization",
                verbose_name="Organization",
            ),
            preserve_default=False,
        ),
    ]
