# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-10-12 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monta_billing", "0026_revenuecode_organization"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RevenueCode",
        ),
    ]
