# Generated by Django 4.1.2 on 2022-10-26 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monta_billing", "0027_delete_revenuecode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingexception",
            name="exception_type",
            field=models.CharField(
                choices=[
                    ("PAPERWORK", "Paperwork"),
                    ("CHARGE", "Charge"),
                    ("CREDIT", "Credit"),
                    ("DEBIT", "Debit"),
                    ("OTHER", "Other"),
                ],
                max_length=10,
                verbose_name="Exception Type",
            ),
        ),
        migrations.AlterField(
            model_name="billinghistory",
            name="bill_type",
            field=models.CharField(
                choices=[
                    ("INVOICE", "Invoice"),
                    ("CREDIT", "Credit"),
                    ("DEBIT", "Debit"),
                    ("PREPAID", "Prepaid"),
                    ("OTHER", "Other"),
                ],
                default="INVOICE",
                max_length=10,
                verbose_name="Bill Type",
            ),
        ),
        migrations.AlterField(
            model_name="billingqueue",
            name="bill_type",
            field=models.CharField(
                choices=[
                    ("INVOICE", "Invoice"),
                    ("CREDIT", "Credit"),
                    ("DEBIT", "Debit"),
                    ("PREPAID", "Prepaid"),
                    ("OTHER", "Other"),
                ],
                default="INVOICE",
                max_length=10,
                verbose_name="Bill Type",
            ),
        ),
    ]
