# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-09-23 00:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("monta_equipment", "0004_equipment_vehicle_license_expiration"),
        ("monta_driver", "0024_alter_driver_organization"),
        ("monta_customer", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("monta_user", "0004_remove_montauser_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="Movement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="AVAILABLE",
                        max_length=20,
                    ),
                ),
                (
                    "assigned_driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        related_query_name="movement",
                        to="monta_driver.driver",
                    ),
                ),
                (
                    "assigned_driver_2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements_2",
                        related_query_name="movement_2",
                        to="monta_driver.driver",
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        related_query_name="movement",
                        to="monta_equipment.equipmenttype",
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Stop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("origin_address", models.CharField(max_length=255)),
                (
                    "origin_appointment_time",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2022, 9, 23, 0, 10, 56, 395454, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                ("destination_address", models.CharField(max_length=255)),
                (
                    "destination_appointment_time",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2022, 9, 23, 0, 10, 56, 395477, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "stop_type",
                    models.CharField(
                        choices=[
                            ("PICKUP", "Pickup"),
                            ("SPLIT_PICKUP", "Split Pickup"),
                            ("SPLIT_DROP_OFF", "Split Drop Off"),
                            ("DELIVERY", "Delivery"),
                            ("DROP_OFF", "Drop Off"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="AVAILABLE",
                        max_length=20,
                    ),
                ),
                (
                    "movement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stops",
                        related_query_name="stop",
                        to="monta_order.movement",
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="AVAILABLE",
                        max_length=20,
                    ),
                ),
                (
                    "mileage",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Total Mileage"
                    ),
                ),
                (
                    "additional_charge",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Additional Charge Amount",
                    ),
                ),
                (
                    "freight_charge",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Freight Charge Amount",
                    ),
                ),
                (
                    "rate_method",
                    models.CharField(
                        choices=[
                            ("FLAT", "Flat"),
                            ("PER_MILE", "Per Mile"),
                            ("PER_STOP", "Per Stop"),
                            ("POUNDS", "Pounds"),
                        ],
                        default="FLAT",
                        max_length=20,
                        verbose_name="Rating Method",
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Freight Charge Amount",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, null=True, verbose_name="Freight Charge Amount"
                    ),
                ),
                (
                    "sub_total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("bill_date", models.DateField(blank=True, null=True)),
                ("entry_date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        related_query_name="order",
                        to="monta_customer.customer",
                    ),
                ),
                (
                    "equipment_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        related_query_name="order",
                        to="monta_equipment.equipmenttype",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        related_query_name="order",
                        to="monta_user.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        related_query_name="order",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="movement",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movements",
                related_query_name="movement",
                to="monta_order.order",
            ),
        ),
    ]
