# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-09-23 00:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monta_order", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stop",
            name="destination_appointment_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 9, 23, 0, 16, 52, 34514, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="stop",
            name="origin_appointment_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 9, 23, 0, 16, 52, 34500, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
