# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-09-23 00:17

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monta_order", "0003_alter_stop_destination_appointment_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stop",
            name="destination_appointment_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 9, 23, 0, 17, 24, 816569, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="stop",
            name="origin_appointment_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 9, 23, 0, 17, 24, 816555, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
