# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-09-25 23:54

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("monta_user", "0004_remove_montauser_is_active"),
        ("monta_order", "0006_stop_sequence_alter_movement_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                related_query_name="order",
                to="monta_user.organization",
                verbose_name="Organization",
            ),
        ),
        migrations.AlterField(
            model_name="stop",
            name="sequence",
            field=models.PositiveIntegerField(default=1, verbose_name="Sequence"),
        ),
        migrations.CreateModel(
            name="OrderType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "order_type_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="Order Type ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="Name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_types",
                        to="monta_user.organization",
                        verbose_name="Organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order Type",
                "verbose_name_plural": "Order Types",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="order",
            name="order_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                related_query_name="order",
                to="monta_order.ordertype",
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="ordertype",
            index=models.Index(fields=["name"], name="monta_order_name_2c4881_idx"),
        ),
    ]
