# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-09-26 00:52

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monta_user", "0004_remove_montauser_is_active"),
        ("monta_order", "0007_alter_order_organization_alter_stop_sequence_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordertype",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="ordertype",
            name="order_type_id",
            field=models.SlugField(
                default=1,
                help_text="Order Type ID",
                max_length=150,
                unique=True,
                verbose_name="Order Type ID",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="DelayCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "delay_code_id",
                    models.SlugField(
                        max_length=255, unique=True, verbose_name="Delay Code ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name",
                        max_length=255,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delay_codes",
                        to="monta_user.organization",
                        verbose_name="Organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Delay Code",
                "verbose_name_plural": "Delay Codes",
                "ordering": ("delay_code_id", "name"),
            },
        ),
        migrations.AddIndex(
            model_name="delaycode",
            index=models.Index(
                fields=["delay_code_id", "name"], name="monta_order_delay_c_755a70_idx"
            ),
        ),
    ]
