# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-09-26 01:02

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monta_user", "0004_remove_montauser_is_active"),
        ("monta_hazardous_material", "0001_initial"),
        (
            "monta_order",
            "0008_alter_ordertype_name_alter_ordertype_order_type_id_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Commodity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "commodity_id",
                    models.SlugField(
                        max_length=255, unique=True, verbose_name="Commodity ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name",
                        max_length=255,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "is_hazardous",
                    models.BooleanField(
                        default=False, help_text="Is Hazmat", verbose_name="Is Hazmat"
                    ),
                ),
                (
                    "hazmat_class",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commodities",
                        to="monta_hazardous_material.hazardousclass",
                        verbose_name="Hazardous Class",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commodities",
                        to="monta_user.organization",
                        verbose_name="Organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Commodity",
                "verbose_name_plural": "Commodities",
                "ordering": ("commodity_id", "name"),
            },
        ),
        migrations.AddField(
            model_name="order",
            name="commodity",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                related_query_name="order",
                to="monta_order.commodity",
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="commodity",
            index=models.Index(
                fields=["commodity_id", "name"], name="monta_order_commodi_6fd8af_idx"
            ),
        ),
    ]
