# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-09-26 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monta_order", "0010_remove_order_rate_alter_order_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="mileage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Total Mileage",
            ),
        ),
    ]
