# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-09-26 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monta_order", "0011_alter_order_mileage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ["order_id"],
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
            },
        ),
        migrations.AddField(
            model_name="order",
            name="order_id",
            field=models.CharField(
                blank=True,
                help_text="Order ID",
                max_length=10,
                null=True,
                unique=True,
                verbose_name="Order ID",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["order_id"], name="monta_order_order_i_5b06bf_idx"
            ),
        ),
    ]
