# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-09-26 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monta_order", "0012_alter_order_options_order_order_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="movement",
            options={
                "ordering": ["order"],
                "verbose_name": "Movement",
                "verbose_name_plural": "Movements",
            },
        ),
        migrations.AddIndex(
            model_name="movement",
            index=models.Index(fields=["order"], name="monta_order_order_i_a166f6_idx"),
        ),
    ]
