# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-09-26 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monta_equipment", "0005_alter_equipment_state"),
        ("monta_driver", "0025_alter_driver_options"),
        ("monta_order", "0013_alter_movement_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movement",
            name="assigned_driver_2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movements_two",
                related_query_name="movement_two",
                to="monta_driver.driver",
            ),
        ),
        migrations.AlterField(
            model_name="movement",
            name="equipment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movements",
                related_query_name="movement",
                to="monta_equipment.equipment",
            ),
        ),
    ]
