# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-09-26 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monta_order", "0014_alter_movement_assigned_driver_2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movement",
            name="status",
            field=models.CharField(
                choices=[
                    ("AVAILABLE", "Available"),
                    ("IN_PROGRESS", "In Progress"),
                    ("COMPLETED", "Completed"),
                ],
                default="AVAILABLE",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
