# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-09-26 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monta_order", "0015_alter_movement_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="entry_date",
        ),
        migrations.AlterField(
            model_name="movement",
            name="status",
            field=models.CharField(
                choices=[
                    ("AVAILABLE", "Available"),
                    ("IN_PROGRESS", "In Progress"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="AVAILABLE",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("AVAILABLE", "Available"),
                    ("IN_PROGRESS", "In Progress"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="AVAILABLE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="stop",
            name="status",
            field=models.CharField(
                choices=[
                    ("AVAILABLE", "Available"),
                    ("IN_PROGRESS", "In Progress"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="AVAILABLE",
                max_length=20,
            ),
        ),
    ]
