# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-09-26 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monta_order", "0017_alter_stop_options_movement_organization_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stop",
            name="sequence",
            field=models.PositiveIntegerField(
                blank=True, default=1, null=True, verbose_name="Sequence"
            ),
        ),
    ]
