# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-09-26 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monta_order", "0018_alter_stop_sequence"),
    ]

    operations = [
        migrations.AddField(
            model_name="stop",
            name="destination_arrival_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Destination Arrival Time"
            ),
        ),
        migrations.AddField(
            model_name="stop",
            name="origin_arrival_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Origin Arrival Time"
            ),
        ),
        migrations.AlterField(
            model_name="stop",
            name="destination_address",
            field=models.CharField(max_length=255, verbose_name="Destination Address"),
        ),
        migrations.AlterField(
            model_name="stop",
            name="destination_appointment_time",
            field=models.DateTimeField(verbose_name="Destination Appointment Time"),
        ),
        migrations.AlterField(
            model_name="stop",
            name="origin_address",
            field=models.CharField(max_length=255, verbose_name="Origin Address"),
        ),
        migrations.AlterField(
            model_name="stop",
            name="origin_appointment_time",
            field=models.DateTimeField(verbose_name="Origin Appointment Time"),
        ),
    ]
