# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-09-26 05:21

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monta_user", "0004_remove_montauser_is_active"),
        ("monta_order", "0019_stop_destination_arrival_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delaycode",
            name="delay_code_id",
            field=models.SlugField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Delay Code ID",
            ),
        ),
        migrations.CreateModel(
            name="ServiceIncident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "delay_reason",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Delay Reason",
                    ),
                ),
                (
                    "delay_time",
                    models.DurationField(
                        blank=True, null=True, verbose_name="Delay Time"
                    ),
                ),
                (
                    "delay_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_incidents",
                        related_query_name="service_incident",
                        to="monta_order.delaycode",
                        verbose_name="Delay Code",
                    ),
                ),
                (
                    "movement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_incidents",
                        related_query_name="service_incident",
                        to="monta_order.movement",
                        verbose_name="Movement",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_incidents",
                        related_query_name="service_incident",
                        to="monta_user.organization",
                        verbose_name="Organization",
                    ),
                ),
                (
                    "stop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_incidents",
                        related_query_name="service_incident",
                        to="monta_order.stop",
                        verbose_name="Stop",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Incident",
                "verbose_name_plural": "Service Incidents",
                "ordering": ["movement"],
            },
        ),
        migrations.AddIndex(
            model_name="serviceincident",
            index=models.Index(
                fields=["movement"], name="monta_order_movemen_d45fd4_idx"
            ),
        ),
    ]
