# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-09-27 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monta_order", "0020_alter_delaycode_delay_code_id_serviceincident_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="freight_charge",
            new_name="freight_charge_amount",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="additional_charge",
            new_name="other_charge_amount",
        ),
    ]
