# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-09-27 04:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("monta_customer", "0004_alter_customer_customer_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "monta_order",
            "0021_rename_freight_charge_order_freight_charge_amount_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="commodity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                related_query_name="order",
                to="monta_order.commodity",
                verbose_name="Commodity",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                related_query_name="order",
                to="monta_customer.customer",
                verbose_name="Customer",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="freight_charge_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Freight Charge Amount",
                max_digits=10,
                null=True,
                verbose_name="Freight Charge Amount",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="mileage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total Mileage",
                max_digits=10,
                null=True,
                verbose_name="Total Mileage",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                related_query_name="order",
                to="monta_order.ordertype",
                verbose_name="Order Type",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="other_charge_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Additional Charge Amount",
                max_digits=10,
                null=True,
                verbose_name="Additional Charge Amount",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("AVAILABLE", "Available"),
                    ("IN_PROGRESS", "In Progress"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="AVAILABLE",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                related_query_name="order",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
