# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-09-27 04:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monta_equipment", "0005_alter_equipment_state"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("monta_order", "0022_alter_order_commodity_alter_order_customer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="bill_date",
            field=models.DateField(
                blank=True,
                help_text="Billed Date",
                null=True,
                verbose_name="Billed Date",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="Planning Comment",
                null=True,
                verbose_name="Planning Comment",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="equipment_type",
            field=models.ForeignKey(
                help_text="Equipment Type",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                related_query_name="order",
                to="monta_equipment.equipmenttype",
                verbose_name="Equipment Type",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="rate_method",
            field=models.CharField(
                choices=[
                    ("FLAT", "Flat"),
                    ("PER_MILE", "Per Mile"),
                    ("PER_STOP", "Per Stop"),
                    ("POUNDS", "Pounds"),
                ],
                default="FLAT",
                help_text="Rating Method",
                max_length=20,
                verbose_name="Rating Method",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="sub_total",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Sub Total Amount",
                max_digits=10,
                null=True,
                verbose_name="Sub Total Amount",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                help_text="Order entered by User",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                related_query_name="order",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
