# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-09-27 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monta_order", "0023_alter_order_bill_date_alter_order_comment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="billing_transfer_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Billing Transfer Date",
                null=True,
                verbose_name="Billing Transfer Date",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="transferred_to_billing",
            field=models.BooleanField(
                default=False,
                help_text="Transferred to Billing",
                verbose_name="Transferred to Billing",
            ),
        ),
    ]
