# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-09-27 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monta_order", "0024_order_billing_transfer_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="ready_to_bill",
            field=models.BooleanField(
                default=False, help_text="Ready to Bill", verbose_name="Ready to Bill"
            ),
        ),
    ]
