# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-09-27 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monta_order", "0025_order_ready_to_bill"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stop",
            name="destination_appointment_time",
            field=models.DateTimeField(
                help_text="The time the equipment is expected to arrive at the destination.",
                verbose_name="Destination Appointment Time",
            ),
        ),
        migrations.AlterField(
            model_name="stop",
            name="origin_appointment_time",
            field=models.DateTimeField(
                help_text="The time the equipment is expected to arrive at the origin/pickup.",
                verbose_name="Origin Appointment Time",
            ),
        ),
    ]
