# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-09-27 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("monta_locations", "0004_alter_location_location_id"),
        ("monta_order", "0026_alter_stop_destination_appointment_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stop",
            name="destination_location",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="destination_stops",
                related_query_name="destination_stop",
                to="monta_locations.location",
                verbose_name="Destination Location ID",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stop",
            name="origin_location",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="origin_stops",
                related_query_name="origin_stop",
                to="monta_locations.location",
                verbose_name="Origin Location ID",
            ),
            preserve_default=False,
        ),
    ]
