# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-09-27 15:41

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models

import monta_order.models


class Migration(migrations.Migration):

    dependencies = [
        ("monta_user", "0004_remove_montauser_is_active"),
        ("monta_customer", "0010_alter_customerbillingprofile_options_and_more"),
        ("monta_order", "0027_stop_destination_location_stop_origin_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderDocumentation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=monta_order.models.order_documentation_upload_to,
                        verbose_name="Document",
                    ),
                ),
                (
                    "document_class",
                    models.ForeignKey(
                        help_text="Document Class",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_documentation",
                        to="monta_customer.documentclassification",
                        verbose_name="Document Class",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_documentation",
                        to="monta_order.order",
                        verbose_name="Order",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_documentation",
                        to="monta_user.organization",
                        verbose_name="Organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order Documentation",
                "verbose_name_plural": "Order Documentation",
                "ordering": ["order"],
            },
        ),
        migrations.AddIndex(
            model_name="orderdocumentation",
            index=models.Index(fields=["order"], name="monta_order_order_i_fa3977_idx"),
        ),
    ]
