# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-09-27 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monta_order", "0028_orderdocumentation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="billed",
            field=models.BooleanField(
                default=False, help_text="Billed", verbose_name="Billed"
            ),
        ),
    ]
