# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-09-28 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monta_user", "0005_alter_profile_state_alter_profile_zip_code"),
        ("monta_order", "0029_order_billed"),
    ]

    operations = [
        migrations.AddField(
            model_name="stop",
            name="organization",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="stops",
                related_query_name="stop",
                to="monta_user.organization",
                verbose_name="Organization",
            ),
            preserve_default=False,
        ),
    ]
