# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-09-29 22:49

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ("monta_locations", "0004_alter_location_location_id"),
        ("monta_order", "0030_stop_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="destination_address",
            field=models.CharField(
                default=1, max_length=255, verbose_name="Destination Address"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="destination_appointment_time",
            field=models.DateTimeField(
                default=timezone.now,
                help_text="The time the equipment is expected to arrive at the destination.",
                verbose_name="Destination Appointment Time",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="destination_arrival_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Destination Arrival Time"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="destination_location",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="destination_orders",
                related_query_name="destination_order",
                to="monta_locations.location",
                verbose_name="Destination Location",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="origin_address",
            field=models.CharField(
                default=1, max_length=255, verbose_name="Origin Address"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="origin_appointment_time",
            field=models.DateTimeField(
                default=timezone.now,
                help_text="The time the equipment is expected to arrive at the origin/pickup.",
                verbose_name="Origin Appointment Time",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="origin_arrival_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Origin Arrival Time"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="origin_location",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="origin_orders",
                related_query_name="origin_order",
                to="monta_locations.location",
                verbose_name="Origin Location",
            ),
            preserve_default=False,
        ),
    ]
