# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-09-29 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monta_order", "0031_order_destination_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="destination_arrival_time",
        ),
        migrations.RemoveField(
            model_name="order",
            name="origin_arrival_time",
        ),
        migrations.AlterField(
            model_name="order",
            name="destination_address",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Destination Address",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="destination_appointment_time",
            field=models.DateTimeField(
                blank=True,
                help_text="The time the equipment is expected to arrive at the destination.",
                null=True,
                verbose_name="Destination Appointment Time",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="origin_address",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Origin Address"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="origin_appointment_time",
            field=models.DateTimeField(
                blank=True,
                help_text="The time the equipment is expected to arrive at the origin/pickup.",
                null=True,
                verbose_name="Origin Appointment Time",
            ),
        ),
    ]
