# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-09-29 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monta_driver", "0029_alter_drivercontact_driver_and_more"),
        ("monta_order", "0032_remove_order_destination_arrival_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movement",
            name="assigned_driver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movements",
                related_query_name="movement",
                to="monta_driver.driver",
                verbose_name="Assigned Driver",
            ),
        ),
    ]
