# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-09-29 23:36

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ("monta_locations", "0004_alter_location_location_id"),
        ("monta_order", "0033_alter_movement_assigned_driver"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stop",
            name="destination_address",
        ),
        migrations.RemoveField(
            model_name="stop",
            name="destination_appointment_time",
        ),
        migrations.RemoveField(
            model_name="stop",
            name="destination_arrival_time",
        ),
        migrations.RemoveField(
            model_name="stop",
            name="destination_location",
        ),
        migrations.RemoveField(
            model_name="stop",
            name="origin_address",
        ),
        migrations.RemoveField(
            model_name="stop",
            name="origin_appointment_time",
        ),
        migrations.RemoveField(
            model_name="stop",
            name="origin_arrival_time",
        ),
        migrations.RemoveField(
            model_name="stop",
            name="origin_location",
        ),
        migrations.AddField(
            model_name="stop",
            name="address_line",
            field=models.CharField(
                default=1, max_length=255, verbose_name="Stop Address"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stop",
            name="appointment_time",
            field=models.DateTimeField(
                default=timezone.now,
                help_text="The time the equipment is expected to arrive at the stop.",
                verbose_name="Stop Appointment Time",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stop",
            name="arrival_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Stop Arrival Time"
            ),
        ),
        migrations.AddField(
            model_name="stop",
            name="departure_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Stop Departure Time"
            ),
        ),
        migrations.AddField(
            model_name="stop",
            name="location",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stops",
                related_query_name="stop",
                to="monta_locations.location",
                verbose_name="Location",
            ),
            preserve_default=False,
        ),
    ]
