# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-10-02 02:16

from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


class Migration(migrations.Migration):
    dependencies = [
        ("monta_user", "0005_alter_profile_state_alter_profile_zip_code"),
        ("monta_order", "0034_remove_stop_destination_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movement",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movements",
                related_query_name="movement",
                to="monta_order.order",
                verbose_name="Order",
            ),
        ),
        migrations.AlterField(
            model_name="movement",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movements",
                related_query_name="movement",
                to="monta_user.organization",
                verbose_name="Organization",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="destination_appointment_time",
            field=models.DateTimeField(
                default=timezone.now,
                help_text="The time the equipment is expected to arrive at the destination.",
                verbose_name="Destination Appointment Time",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                related_query_name="order",
                to="monta_user.organization",
                verbose_name="Organization",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="origin_appointment_time",
            field=models.DateTimeField(
                default=timezone.now,
                help_text="The time the equipment is expected to arrive at the origin/pickup.",
                verbose_name="Origin Appointment Time",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="stop",
            name="movement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stops",
                related_query_name="stop",
                to="monta_order.movement",
            ),
        ),
        migrations.AlterField(
            model_name="stop",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stops",
                related_query_name="stop",
                to="monta_user.organization",
                verbose_name="Organization",
            ),
        ),
    ]
