# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-10-02 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("monta_locations", "0005_alter_location_latitude_alter_location_longitude"),
        (
            "monta_order",
            "0035_alter_movement_order_alter_movement_organization_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="destination_location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="destination_orders",
                related_query_name="order",
                to="monta_locations.location",
                verbose_name="Destination Location",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="origin_location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="origin_orders",
                related_query_name="order",
                to="monta_locations.location",
                verbose_name="Origin Location",
            ),
        ),
    ]
