# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-10-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monta_order", "0038_alter_serviceincident_stop"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="pieces",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                help_text="Total Pieces",
                null=True,
                verbose_name="Pieces",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="weight",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                help_text="Total Weight",
                null=True,
                verbose_name="Weight",
            ),
        ),
        migrations.AddField(
            model_name="stop",
            name="pieces",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                help_text="Pieces",
                null=True,
                verbose_name="Pieces",
            ),
        ),
        migrations.AddField(
            model_name="stop",
            name="weight",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                help_text="Weight",
                null=True,
                verbose_name="Weight",
            ),
        ),
    ]
