# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-10-12 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("monta_user", "0008_alter_profile_address_alter_profile_bio_and_more"),
        ("monta_locations", "0008_locationcontact_organization"),
        ("monta_order", "0039_order_pieces_order_weight_stop_pieces_stop_weight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stop",
            name="address_line",
            field=models.CharField(
                help_text="Stop Address", max_length=255, verbose_name="Stop Address"
            ),
        ),
        migrations.AlterField(
            model_name="stop",
            name="arrival_time",
            field=models.DateTimeField(
                blank=True,
                help_text="The time the equipment actually arrived at the stop.",
                null=True,
                verbose_name="Stop Arrival Time",
            ),
        ),
        migrations.AlterField(
            model_name="stop",
            name="departure_time",
            field=models.DateTimeField(
                blank=True,
                help_text="The time the equipment actually departed from the stop.",
                null=True,
                verbose_name="Stop Departure Time",
            ),
        ),
        migrations.AlterField(
            model_name="stop",
            name="location",
            field=models.ForeignKey(
                help_text="The location of the stop.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stops",
                related_query_name="stop",
                to="monta_locations.location",
                verbose_name="Location",
            ),
        ),
        migrations.AlterField(
            model_name="stop",
            name="movement",
            field=models.ForeignKey(
                help_text="The movement that the stop belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stops",
                related_query_name="stop",
                to="monta_order.movement",
                verbose_name="Movement",
            ),
        ),
        migrations.AlterField(
            model_name="stop",
            name="organization",
            field=models.ForeignKey(
                help_text="The organization that the stop belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stops",
                related_query_name="stop",
                to="monta_user.organization",
                verbose_name="Organization",
            ),
        ),
        migrations.AlterField(
            model_name="stop",
            name="sequence",
            field=models.PositiveIntegerField(
                blank=True,
                default=1,
                help_text="The sequence of the stop in the movement.",
                null=True,
                verbose_name="Sequence",
            ),
        ),
        migrations.AlterField(
            model_name="stop",
            name="status",
            field=models.CharField(
                choices=[
                    ("AVAILABLE", "Available"),
                    ("IN_PROGRESS", "In Progress"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="AVAILABLE",
                help_text="The status of the stop.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="stop",
            name="stop_type",
            field=models.CharField(
                choices=[
                    ("PICKUP", "Pickup"),
                    ("SPLIT_PICKUP", "Split Pickup"),
                    ("SPLIT_DROP_OFF", "Split Drop Off"),
                    ("DELIVERY", "Delivery"),
                    ("DROP_OFF", "Drop Off"),
                ],
                help_text="The type of stop.",
                max_length=20,
            ),
        ),
    ]
