# Generated by Django 4.1.1 on 2022-10-12 05:01

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("monta_user", "0008_alter_profile_address_alter_profile_bio_and_more"),
        (
            "monta_order",
            "0040_alter_stop_address_line_alter_stop_arrival_time_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="RevenueCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Code of the Revenue Code",
                        max_length=5,
                        unique=True,
                        verbose_name="Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the Revenue Code",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization that the revenue code belongs to.",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="revenue_codes",
                        related_query_name="revenue_code",
                        to="monta_user.organization",
                        verbose_name="Organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Revenue Code",
                "verbose_name_plural": "Revenue Codes",
                "ordering": ["code"],
            },
        ),
        migrations.AddField(
            model_name="order",
            name="revenue_code",
            field=models.ForeignKey(
                blank=True,
                help_text="Revenue Code",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                related_query_name="order",
                to="monta_order.revenuecode",
                verbose_name="Revenue Code",
            ),
        ),
    ]
