# -*- coding: utf-8 -*-
# Generated by Django 4.1.1 on 2022-10-13 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "monta_hazardous_material",
            "0004_hazardousmaterial_remove_hazardousclass_organization",
        ),
        ("monta_order", "0041_revenuecode_order_revenue_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="bol_number",
            field=models.CharField(
                blank=True,
                help_text="BOL Number",
                max_length=255,
                null=True,
                verbose_name="BOL Number",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="consignee_ref_num",
            field=models.CharField(
                blank=True,
                help_text="Consignee Reference Number",
                max_length=255,
                null=True,
                verbose_name="Consignee Reference Number",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="hazmat_id",
            field=models.ForeignKey(
                blank=True,
                help_text="Hazardous Class",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                related_query_name="order",
                to="monta_hazardous_material.hazardousmaterial",
                verbose_name="Hazardous Class",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="temperature_max",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Maximum Temperature",
                max_digits=10,
                null=True,
                verbose_name="Maximum Temperature",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="temperature_min",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Minimum Temperature",
                max_digits=10,
                null=True,
                verbose_name="Minimum Temperature",
            ),
        ),
        migrations.AlterField(
            model_name="commodity",
            name="hazmat_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commodities",
                to="monta_hazardous_material.hazardousmaterial",
                verbose_name="Hazardous Class",
            ),
        ),
    ]
