# Generated by Django 4.1.2 on 2022-10-20 14:13

import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monta_order", "0044_alter_ordertype_order_type_id"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="stop",
            name="stops_protect_redundant_updates",
        ),
    ]
