# Generated by Django 4.1.2 on 2022-10-27 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monta_order", "0045_remove_stop_stops_protect_redundant_updates"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="revenuecode",
            options={
                "ordering": ["name"],
                "verbose_name": "Revenue Code",
                "verbose_name_plural": "Revenue Codes",
            },
        ),
        migrations.RemoveField(
            model_name="revenuecode",
            name="code",
        ),
        migrations.AddField(
            model_name="revenuecode",
            name="name",
            field=models.CharField(
                default=1,
                help_text="Name of the Revenue Code",
                max_length=5,
                unique=True,
                verbose_name="Name",
            ),
            preserve_default=False,
        ),
    ]
